### ISSUE TITLE
Upload retry logic throws exception: "The request message was already sent. Cannot send the same request message multiple times."

### ISSUE THREAD

**Issue by danports** [coryrwest/B2.NET#42]
Sending the same HTTP message instance is exactly what the retry logic attempts to do: https://github.com/coryrwest/B2.NET/blob/5876301d12cb97258afaa22d958b0d341ace2a28/src/Files.cs#L207

Stack trace:
```
System.InvalidOperationException: The request message was already sent. Cannot send the same request message multiple times.
   at System.Net.Http.HttpClient.CheckRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at B2Net.Files.Upload(Byte[] fileData, String fileName, B2UploadUrl uploadUrl, String contentType, Boolean autoRetry, String bucketId, Dictionary`2 fileInfo, CancellationToken cancelToken)
   at B2Net.Files.Upload(Byte[] fileData, String fileName, B2UploadUrl uploadUrl, Boolean autoRetry, String bucketId, Dictionary`2 fileInfo, CancellationToken cancelToken)
```

**Comment by coryrwest** [comment]
Fixed in 0.7.5

**Comment by danports** [comment]
Haven't run into this issue recently (had 42,000 files to upload over the weekend so I hit many of the B2 failure cases), but the fix looks good. 👍
