### ISSUE TITLE
B2Client lifetime may exceed authorization token lifetime

### ISSUE THREAD

**Issue by danports** [coryrwest/B2.NET#44]
According to the [`b2_authorize_account` API documentation](https://www.backblaze.com/b2/docs/b2_authorize_account.html), the returned authorization token is valid for "at most 24 hours". However, the B2Client instance lifetime could exceed this (e.g. if it is created as a singleton in a long-running application). While this could be handled at the application level, it would be nice if B2Client could automatically detect an expired token and generate a new one.

**Comment by coryrwest** [comment]
This is a good catch. I will take care of this soon.

**Comment by danports** [comment]
I think I'm running into this now, though I can't be sure from the stack trace:
```
B2Net.Models.B2Exception
   at B2Net.Utilities.CheckForErrors(HttpResponseMessage response, String callingApi)
   at B2Net.Http.ResponseParser.ParseResponse[T](HttpResponseMessage response, String callingApi)
   at B2Net.Files.GetUploadUrl(String bucketId, CancellationToken cancelToken)
```

One simple workaround is to use a different lifecycle for the `B2Client` (e.g. scoped), but that's not ideal since it means incurring many more `b2_authorize_account` calls, which do have a (small) cost, both in terms of 💵 and 🕐.

**Comment by coryrwest** [comment]
Will be released in version 0.8

**Comment by ViniciusLucas14** [comment]
issue still persists
